### ISSUE TITLE
hha?

### ISSUE THREAD

**Issue by SAV-404** [dinhduynhat/Agarvn#2]
is it v72?..if it is, plz tell me how do i make two inputes, first one is where to put skin names and the second will be for nickNames.
i really need ur help @dinhduynhat .
like this : 
![capture](https://user-images.githubusercontent.com/26459304/36903026-39fed202-1de1-11e8-8f71-cee0a2aedd74.PNG)

**Comment by SAV-404** [comment]
i fixed it, thanks for not helping me!

**Comment by dinhduynhat** [comment]
damnnn. sr bro. I stopped developing it

**Comment by SAV-404** [comment]
it's fine.
